# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']

  # Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      # Run the linter
      - id: ruff
        name: Ruff linter
        args: [--fix]
        exclude: ^alembic/
      # Run the formatter
      - id: ruff-format
        name: Ruff formatter
        exclude: ^alembic/
