line-length = 79
indent-width = 4

exclude = [".venv"]

[lint]
select = ["I", "F", "E", "PL", "PT"]

[lint.per-file-ignores]
"tests/**" = [
    "PLR2004",  # Magic value used in comparison - OK in tests
    "PLC0415",  # Import should be at top-level - OK for test isolation
]

[format]
quote-style = "double"
indent-style = "tab"
