"""add_created_at_column

Revision ID: 04d78d97baeb
Revises: 393542dfe827
Create Date: 2025-10-27 13:34:03.956334

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04d78d97baeb"
down_revision: Union[str, Sequence[str], None] = "393542dfe827"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	# Add column with server default for existing records
	op.add_column(
		"urls",
		sa.Column(
			"created_at",
			sa.DateTime(),
			nullable=False,
			server_default=sa.func.now(),
		),
	)
	# Remove server default (SQLAlchemy will handle defaults for new records)
	op.alter_column("urls", "created_at", server_default=None)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("urls", "created_at")
	# ### end Alembic commands ###
