name: Server CI

on:
  push:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "server/**"
      - ".github/workflows/server-ci.yml"

defaults:
  run:
    working-directory: ./server

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: url_shortener_test
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync

      - name: Run tests with coverage
        env:
          TEST_DB_URL: postgresql://test_user:test_pass@localhost:5433/url_shortener_test
        run: |
          uv run pytest --cov=. --cov-report=term --cov-report=xml -v

      - name: Check coverage threshold
        run: |
          uv run coverage report --fail-under=99

  build:
    name: Validate Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync

      - name: Validate application starts
        run: |
          timeout 10s uv run uvicorn app.main:app || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
